export const data = [
  {
    id: 1,
    firstName: "Jagodage",
    lastName: "Asanka",
    imageUrl: "https://i.ibb.co/MDSR6H7/001.png",
  },
  {
    id: 2,
    firstName: "Randika",
    lastName: "Srimal",
    imageUrl: "https://i.ibb.co/Jpcs3vH/002.png",
  },
  {
    id: 3,
    firstName: "Sachintha",
    lastName: "Guruge",
    imageUrl: "https://i.ibb.co/Y7jCHw6/003.png",
  },
  {
    id: 4,
    firstName: "Geeth",
    lastName: "Prasanna",
    imageUrl: "https://i.ibb.co/pvQJqY3/004.png",
  },
  {
    id: 5,
    firstName: "Dhananjaya",
    lastName: "Kumara",
    imageUrl: "https://i.ibb.co/8jN2298/005.png",
  },
  {
    id: 6,
    firstName: "Ranga",
    lastName: "Lakshitha",
    imageUrl: "https://i.ibb.co/Jm4J82Q/006.png",
  },
  {
    id: 7,
    firstName: "Lahiru",
    lastName: "Samishka",
    imageUrl: "https://i.ibb.co/bLkBpyP/007.png",
  },
  {
    id: 8,
    firstName: "Imesh",
    lastName: "Madhuranga",
    imageUrl: "https://i.ibb.co/JRsFPxs/008.png",
  },
  {
    id: 9,
    firstName: "Chethana",
    lastName: "Kalpa",
    imageUrl: "https://i.ibb.co/XbGjwrF/009.png",
  },
  {
    id: 10,
    firstName: "Asanka",
    lastName: "Sanjeewa",
    imageUrl: "https://i.ibb.co/9TntNjg/010.png",
  },
  {
    id: 13,
    firstName: "Pasindu",
    lastName: "Kavinda",
    imageUrl: "https://i.ibb.co/tCxGgrq/013.png",
  },
  {
    id: 16,
    firstName: "Lahiru",
    lastName: "Pramod",
    imageUrl: "https://i.ibb.co/Vw1Zw7d/016.png",
  },
  {
    id: 24,
    firstName: "Shehara",
    lastName: "Thrimavithana",
    imageUrl: "https://i.ibb.co/zX4XwcX/024.png",
  },
  {
    id: 27,
    firstName: "Sahan",
    lastName: "Thathsara",
    imageUrl: "https://i.ibb.co/pKscDr7/027.png",
  },
  {
    id: 28,
    firstName: "Chamika",
    lastName: "Kalhara",
    imageUrl: "https://i.ibb.co/8MzSPPp/028.png",
  },
  {
    id: 29,
    firstName: "Senith",
    lastName: "Pinsara",
    imageUrl: "https://i.ibb.co/3CCx7wt/029.png",
  },
  {
    id: 30,
    firstName: "Pasindu",
    lastName: "Heshan",
    imageUrl: "https://i.ibb.co/C2ghtwF/030.png",
  },
  {
    id: 32,
    firstName: "Susinidu",
    lastName: "Sadeepa",
    imageUrl: "https://i.ibb.co/hH8764K/032.png",
  },
  {
    id: 34,
    firstName: "Suranga",
    lastName: "Sampath",
    imageUrl: "https://i.ibb.co/9TG9V57/034.png",
  },
  {
    id: 36,
    firstName: "Ashan",
    lastName: "Kolambage",
    imageUrl: "https://i.ibb.co/ZNfVb3g/036.png",
  },
  {
    id: 38,
    firstName: "Hasitha",
    lastName: "Sandaruwan",
    imageUrl: "https://i.ibb.co/YX84tgZ/038.png",
  },
  {
    id: 40,
    firstName: "Dilshika",
    lastName: "Priyashan",
    imageUrl: "https://i.ibb.co/z2rkJ76/040.png",
  },
  {
    id: 43,
    firstName: "Dimuthu",
    lastName: "Madushan",
    imageUrl: "https://i.ibb.co/vkPSj3g/043.png",
  },
  {
    id: 44,
    firstName: "Suranjan",
    lastName: "De Silva",
    imageUrl: "https://i.ibb.co/q7TNGkC/044.png",
  },
  {
    id: 46,
    firstName: "Kosala",
    lastName: "Nadun",
    imageUrl: "https://i.ibb.co/jvbNRRs/046.png",
  },
  {
    id: 48,
    firstName: "Ravindu",
    lastName: "Vithanage",
    imageUrl: "https://i.ibb.co/Yt176QS/048.png",
  },
  {
    id: 50,
    firstName: "Thamindu",
    lastName: "Perera",
    imageUrl: "https://i.ibb.co/0crwRsP/050.png",
  },
  {
    id: 51,
    firstName: "Nipun",
    lastName: "Madhushka",
    imageUrl: "https://i.ibb.co/vY7bcJ6/051.png",
  },
  {
    id: 55,
    firstName: "Kawinda",
    lastName: "Randima",
    imageUrl: "https://i.ibb.co/v1VsD5T/055.png",
  },
  {
    id: 58,
    firstName: "Sachindu",
    lastName: "Srilal",
    imageUrl: "https://i.ibb.co/TWQrYJH/058.png",
  },
  {
    id: 59,
    firstName: "Chandeepa",
    lastName: "Rodrigo",
    imageUrl: "https://i.ibb.co/XjXT1QP/059.png",
  },
  {
    id: 60,
    firstName: "Kankanthri",
    lastName: "Dhanasiri",
    imageUrl: "https://i.ibb.co/n3hqKWP/profile.jpg",
  },
  {
    id: 62,
    firstName: "Charith",
    lastName: "Weerarathne",
    imageUrl: "https://i.ibb.co/0DFJ5Vf/062.png",
  },
  {
    id: 63,
    firstName: "Chathuranga",
    lastName: "Priyadarshana",
    imageUrl: "https://i.ibb.co/fdWbYz5/063.jpg",
  },
  {
    id: 64,
    firstName: "Namal",
    lastName: "Kumara",
    imageUrl: "https://i.ibb.co/n3hqKWP/profile.jpg",
  },
  {
    id: 66,
    firstName: "Kosala",
    lastName: "Indrasiri",
    imageUrl: "https://i.ibb.co/z79b7Gr/066.png",
  },
];
