workflow:
 rules:
  - if: $CI_COMMIT_TAG =~ /^v/
    when: always
  - if: $CI_COMMIT_TAG =~ /^tmp/
    when: always

stages:
  - publish
  - deploy

variables:
  CLIENT_TAG_LATEST: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  before_script:
    - apk --update add docker-compose
    - apk --update add sshpass
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CLIENT_TAG_LATEST -f ./docker/files/prod.Dockerfile --target production  .
    - docker push $CLIENT_TAG_LATEST

deploy:
  image: alpine:latest
  stage: deploy
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    # - scp $APP_ENV $SERVER_USER@$SERVER_IP:/docker-deployments/quotation-system/env/api.env
    - ssh $SERVER_USER@$SERVER_IP "cd /docker-deployments/cyber-heaven/frontend && make deploy tag=$CI_COMMIT_TAG"
  environment:
    name: staging
    url: http://139.59.43.71